### ISSUE TITLE
Creating annotation session gets stuck (windows 10)

### ISSUE THREAD

**Issue by FynnBe** [bioimage-io/bioimageio-colab#11]
creating an annotation session gets stuck on Windwos 10, Chrome Version 129.0.6668.100 (Offizieller Build) (64-Bit)

![image](https://github.com/user-attachments/assets/3a5039ed-129e-41b0-978f-501a7a383121)

```console
Mounted folder: compressed_images
Inline Babel script:624 Error creating annotations folder: NotAllowedError: Failed to execute 'getDirectoryHandle' on 'FileSystemDirectoryHandle': The request is not allowed by the user agent or the platform in the current context.
_callee10$ @ Inline Babel script:624
Inline Babel script:2 Uncaught (in promise) NotAllowedError: Failed to execute 'getDirectoryHandle' on 'FileSystemDirectoryHandle': The request is not allowed by the user agent or the platform in the current context.
```

**Comment by FynnBe** [comment]
it worked when I tried again with a 2d tiff tile in a new folder in my home directory...

**Comment by FynnBe** [comment]
but then in the kaibu page I get 

```console
rpc.js:567 Error: RemoteError: Traceback (most recent call last):
             ^^^^^^^^^^^^
  File "/lib/python311.zip/pyodide/webloop.py", line 401, in run_in_executor
    fut.set_result(func(*args))
                   ^^^^^^^^^^^
  Plugin script, line 26, in get_random_image
  File "numpy/random/mtrand.pyx", line 779, in numpy.random.mtrand.RandomState.randint
  File "numpy/random/_bounded_integers.pyx", line 1425, in numpy.random._bounded_integers._rand_int32
ValueError: high <= 0
Exception: Traceback (most recent call last):
             ^^^^^^^^^^^^
  File "/lib/python311.zip/pyodide/webloop.py", line 401, in run_in_executor
    fut.set_result(func(*args))
                   ^^^^^^^^^^^
  Plugin script, line 26, in get_random_image
  File "numpy/random/mtrand.pyx", line 779, in numpy.random.mtrand.RandomState.randint
  File "numpy/random/_bounded_integers.pyx", line 1425, in numpy.random._bounded_integers._rand_int32
ValueError: high <= 0

    at X._decode (rpc.js:1667:19)
    at X._decode (rpc.js:1751:35)
    at X._handle_method (rpc.js:1254:27)
    at X._fire (index.js:404:11)
    at X._on_message (rpc.js:487:12)
    at _websocket.onmessage (websocket-client.js:227:16)
_encode @ rpc.js:567Understand this error
rpc.js:787 Uncaught (in promise) Error: Error: RemoteError: Traceback (most recent call last):
             ^^^^^^^^^^^^
  File "/lib/python311.zip/pyodide/webloop.py", line 401, in run_in_executor
    fut.set_result(func(*args))
                   ^^^^^^^^^^^
  Plugin script, line 26, in get_random_image
  File "numpy/random/mtrand.pyx", line 779, in numpy.random.mtrand.RandomState.randint
  File "numpy/random/_bounded_integers.pyx", line 1425, in numpy.random._bounded_integers._rand_int32
ValueError: high <= 0
Exception: Traceback (most recent call last):
             ^^^^^^^^^^^^
  File "/lib/python311.zip/pyodide/webloop.py", line 401, in run_in_executor
    fut.set_result(func(*args))
                   ^^^^^^^^^^^
  Plugin script, line 26, in get_random_image
  File "numpy/random/mtrand.pyx", line 779, in numpy.random.mtrand.RandomState.randint
  File "numpy/random/_bounded_integers.pyx", line 1425, in numpy.random._bounded_integers._rand_int32
ValueError: high <= 0

    at c._decode (rpc.js:787:19)
    at c._decode (rpc.js:831:35)
    at c._unwrap (rpc.js:863:23)
    at rpc.js:260:29
    at ne._fire (utils.js:863:11)
    at ne.<anonymous> (connection.js:65:16)
```
